name: 'ecommerce_data_model_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'rs_ecommerce_data_model_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  ecommerce_data_model_dbt:
    # Config indicated by + and applies to all files under models/example/
    data_model:
      +materialized: view
    intermediate: 
      +materialized: view

vars:
  event_stream_database: 'warehouse_ginkgo'  #This is the name of database
  event_stream_schema: 'sim_eventstream'     #This is the name of schema
  start_date: '2021-05-01'              #This is the lower bound on date
  end_date: '2022-06-29'                #This is the upper bound on date
  date_format: 'YYYY-MM-DD'             # This is the date format
  lookback_days: [7,30,90,365]          #These are the days upto which the lookback features will be computed
  card_types: ('mastercard', 'visa')    #These are the types of credit cards(in lowercase) that will be considered to check if the user has a credit card 
  product_ref_var: 'product_id'         #This is the name of the property in the tracks calls that uniquely corresponds to the product
  category_ref_var: 'category_l1'       #This is the name of the property in the tracks calls that corresponds to the product category
  properties_product_ref_var: 'properties_product_id'
  session_cutoff_in_sec: 1800           # A session is a continuous sequence of events, as long as the events are within this interval. If two consecutive events occur at an interval of greater than this, a new session is created.
  main_id: 'main_id'

  #table id stitcher
  tbl_id_stitcher: "{{ source('ecommerce', var('id_stitcher_name')) }}"
  id_stitcher_name: 'MATERIAL_DOMAIN_PROFILE__IDSTITCHER_DC3F9DA0_12'
  col_id_stitcher_other_id: 'other_id'
  col_id_stitcher_other_id_type: 'other_id_type'

  #table ecommerce identifies
  tbl_ecommerce_identifies: "{{ source('ecommerce', 'identifies') }}"
  col_ecommerce_identifies_user_id: 'user_id'
  col_ecommerce_identifies_email: 'properties_email'
  col_ecommerce_identifies_birthday: 'properties_birthday'
  col_ecommerce_identifies_country: 'properties_country'
  col_ecommerce_identifies_timestamp: "{{timestamp_call('timestamp')}}"
  col_ecommerce_identifies_campaign_source: 'context_campaign_source'
  col_ecommerce_identifies_device_type: 'context_device_type'
  col_ecommerce_identifies_gender: 'properties_gender'
  col_ecommerce_identifies_state: 'properties_state'

  #table ecommerce tracks
  tbl_ecommerce_tracks: "{{ source('ecommerce', 'tracks') }}"
  col_ecommerce_tracks_user_id: 'user_id'
  col_ecommerce_tracks_timestamp: "{{timestamp_call('timestamp')}}"

  #table ecommerce product_added
  tbl_ecommerce_product_added: "{{ source('ecommerce', 'product_added') }}"
  col_ecommerce_product_added_user_id: 'user_id'
  col_ecommerce_product_added_properties_cart_id: 'properties_cart_id'
  col_ecommerce_product_added_timestamp: "{{timestamp_call('timestamp')}}"

  #table ecommerce order_completed
  tbl_ecommerce_order_completed: "{{ source('ecommerce', 'order_completed') }}"
  col_ecommerce_order_completed_user_id: 'user_id'
  col_ecommerce_order_completed_properties_total: 'properties_total'
  col_ecommerce_order_completed_timestamp: "{{timestamp_call('timestamp')}}"
  col_ecommerce_order_completed_properties_products: 'properties_products'

  #table ecommerce checkout_step_completed
  tbl_ecommerce_checkout_step_completed: "{{ source('ecommerce', 'checkout_step_completed') }}"
  col_ecommerce_checkout_step_completed_user_id: 'user_id'
  col_ecommerce_checkout_step_completed_payment_method: 'properties_payment_method'
  col_ecommerce_checkout_step_completed_timestamp: "{{timestamp_call('timestamp')}}"
